### ISSUE TITLE
通用规则下的资源追踪mod

### ISSUE THREAD

**Issue by TI-130** [fvtt-cn/fvtt-cn-mod-incubation#10]
**这个 MOD 是否已经有过类似的实现了？**

否

**这个 MOD 为什么是通用，而非特定于某个系统下的？**

不同的系统，从龙蛋到DND，都需要追踪例如水或口粮之类的小队资源。

**这个 MOD 的具体作用是什么？**

这个mod应该可以提供一个简单易编辑的图形界面供所有玩家追踪不同的小队共享资源，例如食物，水。一个简单的方格清单应该可以达成目标。

如果可以做得更复杂的话，也许可以提供将游戏内的物品（例如口粮）拖入这个界面，然后在界面中增减这些物品的选项。

**这个 MOD 是否有赏金？**

否

**补充信息**

**Comment by hmqgg** [comment]
我觉得这个要提上开发进度的话，需要一些产品原型图，用以指导功能设计。

目前可能需要更系统性的描述一下功能层级/UI跳转关系等等具体的？

**Comment by hmqgg** [comment]
我先打一个 求助/设计 标签，看看有没有集思广益。

**Comment by hmqgg** [comment]
https://github.com/davelens/fvtt-party-resources
已有实现
