### ISSUE TITLE
发言提示mod

### ISSUE THREAD

**Issue by TI-130** [fvtt-cn/fvtt-cn-mod-incubation#11]
**这个 MOD 是否已经有过类似的实现了？**

否。

**这个 MOD 为什么是通用，而非特定于某个系统下的？**

这个mod理应适用于不同的系统，因为其功能为辅助玩家们进行游戏。

**这个 MOD 的具体作用是什么？**

这个mod会在玩家们按下某个快捷键之后，为该玩家分配一个数字并提示gm该玩家想要发言，该提示最好漂浮在玩家信息的位置，并存留固定的时间，然后玩家们可以按照自己按下按键的顺序发言，这样可以减少玩家们在网团中抢话或是发言被忽视的情况。

**这个 MOD 是否有赏金？**

否

**补充信息**

**Comment by hmqgg** [comment]
感觉是视频会议中“举手”功能，但因为跑团时即使屏幕没被 fvtt 占完，也会被拉走绝大多数注意力，所以依赖视频会议/语音软件的举手功能可能确实不太方便，所以这个是挺合理的需求。

不过 fvtt 本身自带语音/视频功能，所以我比较犹豫在：
1. 其他更依赖 fvtt 内建音视频（我个人主要用其他语音平台）的玩家，可能已经有这个想法并且正在做
2. 这个功能成为 fvtt 官方为内建音视频添加的功能
3. 作为 fvtt 的 mod 而非原生软件的扩展，只能依赖于 WS/HTTP，难以将举手发言优化到最优的延迟，而延迟对于使用“举手发言”功能的体验来说很重要，不然反而有耽误语音团进程的可能

提到这里，其实也有一个 feature 可以加上。我最近在给自己 mod 用 `DF-Hotkeys` 这个库，可以很方便地给一个 mod 填上功能快捷键（且可以自定义按键）的功能，非常适合这个 mod 的场景。

**Comment by hmqgg** [comment]
https://github.com/cswendrowski/FoundryVTT-Raise-My-Hand

果然已经有人做了，issue closed。
