### ISSUE TITLE
Unzip 檔案工具

### ISSUE THREAD

**Issue by zeteticl** [fvtt-cn/fvtt-cn-mod-incubation#12]
**这个 MOD 是否已经有过类似的实现了？**
否

**这个 MOD 为什么是通用，而非特定于某个系统下的？**
因為是所有系統作用

**这个 MOD 的具体作用是什么？**
FVTT只支援單檔案上傳，
而在nodejs 模式時，上傳大量檔案時需要使用FTP 或者其他軟件(其實FVTT檔案管理功能也很差)
非常麻煩，如果可以上傳一個ZIP File 然後解壓，對NODEJS 使用者會比較方便

**这个 MOD 是否有赏金？**
否，或我能力範圍的?

**补充信息**
無

**Comment by hmqgg** [comment]
在 server side 没有跑其他 program 的情况下，没有办法提供 unzip 的 API，供 MOD 调用，毕竟 Foundry 的 MOD 只能在 client side 跑。
但是确实可以在前端解压，然后批量上传。但这样其实更像是做个批量上传 MOD ？
上传有 API: `FilePicker.upload`，可以直接调用，上传 blob。

**Comment by zeteticl** [comment]
原來如此，我忘了mod 是client side only.
我還是乖乖用ftp 上傳或者期待它本體加入這功能吧WW

不然就是做一個批量上傳工具,
可以自動新增Folder的, 這種我可能寫到,
現在我主要是看不懂它調用其他MOD的方法，不知道怎麼做UNZIP 這動作

**Comment by hmqgg** [comment]
unzip 会用到 FVTT 之外的 API，在 client side 先用 JS 读取并 unzip 成一个个的 blob，然后依次将这些 blob 通过 FVTT 的 API：`FilePicker.upload` 上传到 server side 的相应文件夹（该 API 可以指定位置）。
