### ISSUE TITLE
Theatre 的BUG改良

### ISSUE THREAD

**Issue by zeteticl** [fvtt-cn/fvtt-cn-mod-incubation#13]
**这个 MOD 是否已经有过类似的实现了？ 这个 MOD 的具体作用是什么？**
是
名叫 Theatre
有原版，也有漢化版

嚴格來說不是開發MOD, 而是需要DEBUG幫助
但不知為何，我啓用這兩個版本任何一個時，即使FVTT使用英文/正體中文，輸入英文/正體中文，
也會如下圖，換行變成換行符號，
所以尋找DEBUG方法
貌似別人沒有發現這BUG…所以也想了解別人是不是也會這樣…

FVTT: 079  ENGLISH

曾經新增一個WORLD, 只使用Theatre MOD, 換了不同SYSTEM,
也是一樣結果，只要有分行，就會這樣

![image](https://user-images.githubusercontent.com/23254376/117923032-fd506b80-b325-11eb-9196-0b27600433fc.png)

https://github.com/League-of-Foundry-Developers/fvtt-module-theatre
http://www.goddessfantasy.net/bbs/index.php?topic=117304.0

**这个 MOD 为什么是通用，而非特定于某个系统下的？**
因為是修改UI

**这个 MOD 是否有赏金？**
否，或我能做到的?

**补充信息**

**Comment by hmqgg** [comment]
可能是本地问题？比如浏览器、浏览器插件之类？

**Comment by zeteticl** [comment]
> 可能是本地问题？比如浏览器、浏览器插件之类？

使用過 CHROME, 無㾗模式，和EDGE，
得到一樣結果…

**Comment by zeteticl** [comment]
![image](https://user-images.githubusercontent.com/23254376/118255098-6bd82980-b4de-11eb-98d5-3f9040d9e820.png)
試了使用windows 版的FVTT 
全新安裝，但還是得到同樣結果

**Comment by hmqgg** [comment]
复现不了就很神秘。
而且看图，其实他还是重渲染的`<br/>`，和 HTML Code (`<br>`) 不一样。

**Comment by zeteticl** [comment]
> 复现不了就很神秘。
> 而且看图，其实他还是重渲染的`<br/>`，和 HTML Code (`<br>`) 不一样。

「
今天下午看了一遍，它的顯示是把每個字單獨作為一個元素拼接成一句話的，以適配其動畫效果（比如打字機，縮放等）
除非把文字顯示的所有效果刪除，然後重新畫一個文字顯示區域，這工程量很大且麻煩，不建議這樣干。
」
http://www.goddessfantasy.net/bbs/index.php?topic=117304.0
原來是處理手法問題

**Comment by hmqgg** [comment]
> > 复现不了就很神秘。
> > 而且看图，其实他还是重渲染的`<br/>`，和 HTML Code (`<br>`) 不一样。
> 
> 「
> 今天下午看了一遍，它的顯示是把每個字單獨作為一個元素拼接成一句話的，以適配其動畫效果（比如打字機，縮放等）
> 除非把文字顯示的所有效果刪除，然後重新畫一個文字顯示區域，這工程量很大且麻煩，不建議這樣干。
> 」
> http://www.goddessfantasy.net/bbs/index.php?topic=117304.0
> 原來是處理手法問題

这个好改，回头 fork 一下。
