### ISSUE TITLE
簡易系統開發

### ISSUE THREAD

**Issue by zeteticl** [fvtt-cn/fvtt-cn-mod-incubation#16]
**这个 MOD 将用于什么系统？**
就是一個系統

**这个 MOD 是否已经有过类似的实现了？**
是
類似ccfolia的角色卡

**这个 MOD 的具体作用是什么？**
最上面是圖片，名字和速度

主要是有四頁，第一頁是能力
A) 變動屬性 如 HP 10/10  MP 5/5
B) 固定屬性  如STR 50 CON 30
C) 擲骰指令表  3d10<={STR}  但可以使用{STR} {HP.NOW} {HP.MAX}這樣的指令讀取A和B數字

A B 右上角有一個+號可以新增一行出來

C 有edit 和擲骰模式，edit ​為input 格，可以一行一個，
輪入後，可以按鈕轉換為擲骰模式
擲骰就是雙擊那一行，就可以擲骰

第二頁是文字資料
可以輸入背景等等

第三頁也是文字資料
可以輸入道具等等

第四頁是設定
可以改背景等等

![image](https://user-images.githubusercontent.com/23254376/148656101-834dc183-a432-41c8-ba7f-6764670b7915.png)

![image](https://user-images.githubusercontent.com/23254376/148656130-ec47869c-3e94-4076-90f4-4649f281bc57.png)

**这个 MOD 是否有赏金？**
是50USD或可議

**补充信息**

**Comment by hmqgg** [comment]
要说的话已经有 `Sandbox` 或者 `Simple Worldbuilding System` 以及其相关的 MOD 了？

**Comment by zeteticl** [comment]
> 要说的话已经有 `Sandbox` 或者 `Simple Worldbuilding System` 以及其相关的 MOD 了？

我知道啊，不過不夠好用，而我嘗試改`Simple Worldbuilding System`又失敗了……
