### ISSUE TITLE
FVTT 投票 MOD

### ISSUE THREAD

**Issue by hmqgg** [fvtt-cn/fvtt-cn-mod-incubation#5]
**这个 MOD 是否已经有过类似的实现了？**

是。
[Forien's Easy Polls](https://foundryvtt.com/packages/forien-easy-polls)。需要新 MOD 替代的原因是长期未维护，缺少必要功能（如匿名投票、每人一票等等），缺少 API 支持无法用宏或者 MOD 快速创建投票。

**这个 MOD 为什么是通用，而非特定于某个系统下的？**

投票并不依赖于任何系统。

**这个 MOD 的具体作用是什么？**

核心功能是发起投票。
对于发起的投票，可以配置：
- 隐藏结果，开启后，玩家看不到这次投票的结果
- 可更改，开启后，玩家可以更改自己的投票结果
- 匿名，开启后，玩家看不到这次投票中其他人的投票
- 每人 X 票，设定后，每个玩家最多可以投 X 票
- 截止日期，设定后，玩家必须在截止日前投票否则失效
- 选定范围，只有被选定的玩家才能进行投票
- 投票模板，将投票的每个选项以及上述配置项存为模板，每次可以直接从模板新建投票

这个 MOD 需要三个独立对话框，【创建投票对话框】、【进行投票对话框】、【模板管理对话框】。
【创建投票对话框】中提供以上配置选项以及是否保存为模板（带有命名）。
创建投票之后，将投票消息作为一条聊天消息（此处也是一个模板，可以根据该玩家是否已完成投票更改消息内容）发送到聊天框中，仅在选定范围内的玩家才能看见该投票消息（以及进行投票），点击消息中的投票按钮，打开【进行投票对话框】进行投票。
【模板管理对话框】在 MOD 设置界面中打开，可以修改、删除所有创建的投票模板。

**这个 MOD 是否有赏金？**

否。

**补充信息**

无。

**Comment by zeteticl** [comment]
建議結果除了發送到聊天框外，也可以使用Alert 來發送結果，
個人來說，那個聊天框太容易因為洗走訊息而看不清，
尤其投票結果動輒六七行的資訊，可能發起幾次就不知去到那了?

不過我覺得像ROLL20 那樣先攻表那樣，有個獨立浮動表格
如果GM打開表格，玩家也會強制顯示一個表格出來的方式也不錯?

**Comment by hmqgg** [comment]
正在开发中。

**Comment by zeteticl** [comment]
https://github.com/jeremiahverba/afk-ready-check

看到一個可以參考的MOD
