### ISSUE TITLE
日系凍豆平台UI

### ISSUE THREAD

**Issue by zeteticl** [fvtt-cn/fvtt-cn-mod-incubation#6]
**这个 MOD 是否已经有过类似的实现了？**

是
https://github.com/fvtt-cn/FoundryVTT-Tabbed-Chatlog
https://gitlab.com/anathemamask/salon/-/tree/master

因為沒有自定義TAG CHAT 的功能, 只有指定的TAG 
1. OOC 2. ROLLDICE 3. CHARACTER

**这个 MOD 为什么是通用，而非特定于某个系统下的？**

因為這是修改聊天系統

**这个 MOD 的具体作用是什么？**

1. 修改UI - 變成浮動CHAT TAG,  可以橫向顯示文字，可以拖動大小而不是固定，可以開啓多個CHAT TAG, 方便看
2. 自定義TAG, 可以讓GM自行設定TAG如 主要, 聊天, 場外, 擲骰 等等. 當玩家在那一個TAG底下打字, 就會在那個TAG上顯示輸入內容。
3. 在那個CHAT上, 可以放一些快捷鍵, 讓人使用
4. 美化UI,  那些SETTING 標籤上加些文子?  FVTT的UI真的很……那個

示例, 日系TRPG平台UI
![圖片](https://user-images.githubusercontent.com/23254376/112743880-b143a480-8fcd-11eb-8a75-36e2be133117.png)

**这个 MOD 是否有赏金？**

否

**补充信息**

**Comment by hmqgg** [comment]
其实我在想 Salon + 定制化的 Tabbed ChatLog 确实可以满足需求。

Tabchat 来给任意消息打 tag（就是和当前聊天栏一致），Salon用来呈现弹出聊天框的 UI。

大致就是如此？

**Comment by zeteticl** [comment]
期待FVTT孵化WW

**Comment by hmqgg** [comment]
![image](https://user-images.githubusercontent.com/36689909/113425003-afca1000-9403-11eb-92d7-8e919e777dee.png)


https://user-images.githubusercontent.com/36689909/113425162-fd467d00-9403-11eb-8166-2bd582ce6651.mp4

类似的任意聊天消息栏功能，可能之后会推到 FVTT-CN 分支的 Tabbed-ChatLog 上，UI 上自己看看怎么和 Salon 之类的 MOD 配合，似乎就可以了？

**Comment by hmqgg** [comment]
Released, issue closed.
