### ISSUE TITLE
CoC 疯狂表

### ISSUE THREAD

**Issue by kagangtuya-star** [fvtt-cn/fvtt-cn-mod-incubation#8]
**这个 MOD 将用于什么系统？**
CoC7-FoundryVTT [https://github.com/HavlockV/CoC7-FoundryVTT](链接)

**这个 MOD 是否已经有过类似的实现了？**
是
一个疯狂状态随机表，只能手动进行使用 [https://github.com/kagangtuya-star/Fvtt_coc7_crazylist](链接)

**这个 MOD 为什么是这个系统限定的？**

coc7规则特有的疯狂检定规则

**这个 MOD 的具体作用是什么？**

提供一个按键或功能选项，可以手动输入对应的sc数值，如（/sc1/1d6），然后系统自动进行对应的sancheck判定，扣除san值，并调用疯狂随机表输出结果，类同qq骰子机器人

**这个 MOD 是否有赏金？**

是

可以用一个coc7的带图标技能合集包作为赏金，正在做

**补充信息**

**Comment by kagangtuya-star** [comment]
就这样

**Comment by zeteticl** [comment]
有興趣寫w

**Comment by zeteticl** [comment]
https://github.com/hktrpg/FVTT-coc7th-SC

安裝LINK:
https://raw.githubusercontent.com/hktrpg/FVTT-coc7th-SC/main/module.json


初步完成 但
瘋狂表版權問題, 以後才想怎樣搬回過來 及 怎樣弄多國語言版, 以及再美化一下?

P.S.多國語言要處理幾百個瘋狂症,一個一個去取代, 叔叔真的不行了……


功能: 
    San Check by Commond - /sc 1/2d3 
    The Real Time Bout of Madness - /ccrt
    The Summary Bout of Madness - /ccsu
    It will read the san on character sheet
    use on coc7th character sheet from HavlockV/CoC7-FoundryVTT

**Comment by kagangtuya-star** [comment]
联系一下原作者？
另外，那个coc技能合集包已经完成10%了，不过是简体中文的.....







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fvtt-cn/fvtt-cn-mod-incubation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 凌晨2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fvtt-cn/fvtt-cn-mod-incubation] CoC 疯狂表 (#8)





 
https://github.com/hktrpg/FVTT-coc7th-SC
 
瘋狂表版權問題, 以後才想怎樣搬回過來 及 怎樣弄多國語言版, 以及再美化一下?
 
功能:
 San Check by Commond - /sc 1/2d3
 The Real Time Bout of Madness - /ccrt
 The Summary Bout of Madness - /ccsu
 It will read the san on character sheet
 use on coc7th character sheet from HavlockV/CoC7-FoundryVTT

**Comment by kagangtuya-star** [comment]
一些实例效果，已经完成一半了












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fvtt-cn/fvtt-cn-mod-incubation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 凌晨2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fvtt-cn/fvtt-cn-mod-incubation] CoC 疯狂表 (#8)





 
https://github.com/hktrpg/FVTT-coc7th-SC
 
疯狂表版权问题, 以后才想怎样搬回过来及怎样弄多国语言版, 以及再美化一下?
 
功能：
 San Check by Commond-/ sc 1 / 2d3
 实时狂动-/ ccrt狂热
 总结-/ ccsu
 它将
 从HavlockV / CoC7-FoundryVTT读取coc7th字符表上字符表上的san
 
—
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by kagangtuya-star** [comment]
这个问题是怎么解决的









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fvtt-cn/fvtt-cn-mod-incubation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 凌晨2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fvtt-cn/fvtt-cn-mod-incubation] CoC 疯狂表 (#8)





 
https://github.com/hktrpg/FVTT-coc7th-SC
 
疯狂表版权问题, 以后才想怎样搬回过来及怎样弄多国语言版, 以及再美化一下?
 
功能：
 San Check by Commond-/ sc 1 / 2d3
 实时狂动-/ ccrt狂热
 总结-/ ccsu
 它将
 从HavlockV / CoC7-FoundryVTT读取coc7th字符表上字符表上的san
 
—
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by kagangtuya-star** [comment]
看邮箱吧，图片没法同步

**Comment by zeteticl** [comment]
什麼郵箱, 看不到啊WW

**Comment by zeteticl** [comment]
> 
> 
> 看邮箱吧，图片没法同步

什麼郵箱, 看不到啊WW

**Comment by kagangtuya-star** [comment]
啊，我设置的那个与邮箱同步，有其他的联系方式吗
这个发不了图片






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fvtt-cn/fvtt-cn-mod-incubation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 晚上11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fvtt-cn/fvtt-cn-mod-incubation] CoC 疯狂表 (#8)





  
看邮箱吧，图片没法同步
  
什麼郵箱, 看不到啊WW

**Comment by zeteticl** [comment]
> 
> 啊，我设置的那个与邮箱同步，有其他的联系方式吗 这个发不了图片
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fvtt-cn/fvtt-cn-mod-incubation" ***@***.***&gt;; 发送时间:&nbsp;2021年3月30日(星期二) 晚上11:07 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [fvtt-cn/fvtt-cn-mod-incubation] CoC 疯狂表 (#8) 看邮箱吧，图片没法同步 什麼郵箱, 看不到啊WW — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

discord?

**Comment by kagangtuya-star** [comment]
行啊，有discord邀请链接吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月30日(星期二) 晚上11:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fvtt-cn/fvtt-cn-mod-incubation] CoC 疯狂表 (#8)





  
啊，我设置的那个与邮箱同步，有其他的联系方式吗 这个发不了图片
 …
 ------------------ 原始邮件 ------------------ 发件人: "fvtt-cn/fvtt-cn-mod-incubation" @.&gt;; 发送时间: 2021年3月30日(星期二) 晚上11:07 @.&gt;; @.@.&gt;; 主题: Re: [fvtt-cn/fvtt-cn-mod-incubation] CoC 疯狂表 (#8) 看邮箱吧，图片没法同步 什麼郵箱, 看不到啊WW — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
discord?
 
&mdash;

**Comment by zeteticl** [comment]
> 
> 行啊，有discord邀请链接吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月30日(星期二) 晚上11:27 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [fvtt-cn/fvtt-cn-mod-incubation] CoC 疯狂表 (#8) 啊，我设置的那个与邮箱同步，有其他的联系方式吗 这个发不了图片 … ------------------ 原始邮件 ------------------ 发件人: "fvtt-cn/fvtt-cn-mod-incubation" @.&gt;; 发送时间: 2021年3月30日(星期二) 晚上11:07 @.&gt;; @.@.&gt;; 主题: Re: [fvtt-cn/fvtt-cn-mod-incubation] CoC 疯狂表 (#8) 看邮箱吧，图片没法同步 什麼郵箱, 看不到啊WW — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. discord? &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

https://discord.gg/vx4kcm7

**Comment by kagangtuya-star** [comment]
我进去了，昵称是 卡冈图雅 头像是只 小黑猫




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月30日(星期二) 晚上11:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fvtt-cn/fvtt-cn-mod-incubation] CoC 疯狂表 (#8)





  
行啊，有discord邀请链接吗
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年3月30日(星期二) 晚上11:27 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [fvtt-cn/fvtt-cn-mod-incubation] CoC 疯狂表 (#8) 啊，我设置的那个与邮箱同步，有其他的联系方式吗 这个发不了图片 … ------------------ 原始邮件 ------------------ 发件人: "fvtt-cn/fvtt-cn-mod-incubation" @.&gt;; 发送时间: 2021年3月30日(星期二) 晚上11:07 @.&gt;; @.@.&gt;; 主题: Re: [fvtt-cn/fvtt-cn-mod-incubation] CoC 疯狂表 (#8) 看邮箱吧，图片没法同步 什麼郵箱, 看不到啊WW — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. discord? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
https://discord.gg/vx4kcm7
 
&mdash;
